/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x004615b1
int Game_Fn4615b1(int a1, int a2, int a3, int a4)
{
    int iv;   /* [ebp-4] */

    iv = 1;
    if (Game_Helper40cadc(a1, a2) == 0) {
        iv = 0;
    }
    if ((Game_Helper452ad9(a1, a2) & 0x40) == 0) {
        iv = 0;
    }
    return iv;
}

// FUNCTION: SHANDALAR 0x004629be
int Game_Fn4629be(int a1)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */
    int ih;   /* [ebp-12] */
    int ii;   /* [ebp-16] */
    int ij;   /* [ebp-20] */
    int ik;   /* [ebp-24] */
    int il;   /* [ebp-28] */
    int im;   /* [ebp-32] */
    int in;   /* [ebp-36] */
    int io;   /* [ebp-40] */

    Game_Helper56ca10(0x585b84, 0x585b70);
    Game_Helper57e820(0x7beac0, 0x8aa920);
    Game_Helper56ca10(a1, 0x585b98);
    Game_Helper57e820(0x7a01f0, 0x8aa920);
    Game_Helper56ca10(a1, 0x585ba4);
    ih = 0;
    for (iv = 1; iv < 6; iv++) {
        ii = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73bd20, ii * 300 + 0x8aa920);
    }
    for (iv = 1; iv < 6; iv++) {
        ij = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73bea0, ij * 300 + 0x8aa920);
    }
    for (iv = 1; iv < 6; iv++) {
        ik = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73bca0, ik * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585bb0);
    Game_Helper57e820(0x73bd20, 0x8aa920);
    Game_Helper57e820(0x73bea0, 0x8aa920);
    Game_Helper56ca10(a1, 0x585bc0);
    ih = 0;
    for (iv = 1; iv < 6; iv++) {
        il = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73be20, il * 300 + 0x8aa920);
    }
    for (iv = 1; iv < 6; iv++) {
        im = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73bda0, im * 300 + 0x8aa920);
    }
    for (iv = 1; iv < 6; iv++) {
        in = ih;
        ih++;
        Game_Helper57e820(iv * 20 + 0x73bf20, in * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585bcc);
    ih = 0;
    for (iv = 0; iv < 0x11; iv++) {
        io = ih;
        ih++;
        Game_Helper57e820(iv * 50 + 0x8c8f60, io * 300 + 0x8aa920);
    }
    ig = Game_Helper56ca10(a1, 0x585bdc);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 300 + 0x93aa60, iv * 300 + 0x8aa920);
    }
    g_game8e1aa4 = Game_Helper56ca10(a1, 0x585bf4);
    ig = g_game8e1aa4;
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x7a0a10 + 0x1388, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c08);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x7a0a10 + 0x2710, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c1c);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x7a0a10 + 0x3a98, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c30);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x7a0a10 + 0x4e20, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c40);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x7a0a10 + 0x61a8, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c54);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x931390 + 0x1388, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c68);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x931390 + 0x2710, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c7c);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x931390 + 0x3a98, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585c90);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x931390 + 0x4e20, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585ca0);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x931390 + 0x61a8, iv * 300 + 0x8aa920);
    }
    g_game7a09c4 = Game_Helper56ca10(a1, 0x585cb4);
    ig = g_game7a09c4;
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x798960 + 0x1388, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585ccc);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x798960 + 0x2710, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585ce0);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x798960 + 0x3a98, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585cf8);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x798960 + 0x4e20, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d0c);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x798960 + 0x61a8, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d24);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x8bde10 + 0x1388, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d38);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x8bde10 + 0x2710, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d4c);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x8bde10 + 0x3a98, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d60);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x8bde10 + 0x4e20, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d74);
    for (iv = 0; iv < ig; iv++) {
        Game_Helper57e820(iv * 100 + 0x8bde10 + 0x61a8, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(a1, 0x585d88);
    Game_Helper57e820(0x92fe50, 0x8aa920);
    Game_Helper56ca10(a1, 0x585da0);
    Game_Helper57e820(0x7beb30, 0x8aa920);
    Game_Helper57e826(0x7beb30, 0x585dac);
    Game_Helper57e826(0x7beb30, 0x8aa920 + 0x12c);
    Game_Helper57e826(0x7beb30, 0x585db0);
    Game_Helper57e826(0x7beb30, 0x8aa920 + 0x258);
    Game_Helper56ca10(a1, 0x585db4);
    Game_Helper57e820(0x8e0890, 0x8aa920);
    Game_Helper57e820(0x78e700, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x7bf4d0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x931080, 0x8aa920 + 0x384);
    Game_Helper57e820(0x951ab0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8c7ea0, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x7be880, 0x8aa920 + 0x708);
    Game_Helper57e820(0x8c82c0, 0x8aa920 + 0x834);
    Game_Helper56ca10(a1, 0x585dc0);
    Game_Helper57e820(0x92f2a0, 0x8aa920);
    Game_Helper56ca10(a1, 0x585dd4);
    Game_Helper57e820(0x8c89d0, 0x8aa920);
    Game_Helper57e820(0x7a8070, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x8e2410, 0x8aa920 + 0x258);
    Game_Helper56ca10(a1, 0x585de4);
    Game_Helper57e820(0x94d7c0, 0x8aa920);
    Game_Helper57e820(0x94e970, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x93a650, 0x8aa920 + 0x258);
    Game_Helper56ca10(a1, 0x585df8);
    Game_Helper57e820(0x94d330, 0x8aa920);
    Game_Helper57e820(0x7be750, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x8c88a0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x92f420, 0x8aa920 + 0x384);
    Game_Helper57e820(0x7a00b0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x78eac0, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x930240, 0x8aa920 + 0x708);
    Game_Helper57e820(0x8e2fd0, 0x8aa920 + 0x834);
    Game_Helper57e820(0x8c8770, 0x8aa920 + 0x960);
    Game_Helper57e820(0x8bce40, 0x8aa920 + 0xa8c);
    Game_Helper57e820(0x9311b0, 0x8aa920 + 0xbb8);
    Game_Helper57e820(0x9307c0, 0x8aa920 + 0xce4);
    Game_Helper56ca10(0x585e20, 0x585e0c);
    Game_Helper57e820(0x7a04d0, 0x8aa920);
    Game_Helper56ca10(0x585e4c, 0x585e30);
    Game_Helper57e820(0x8c7470, 0x8aa920);
    Game_Helper56ca10(0x585e74, 0x585e5c);
    Game_Helper57e820(0x93a340, 0x8aa920);
    Game_Helper56ca10(0x585e94, 0x585e84);
    Game_Helper57e820(0x7a0370, 0x8aa920);
    Game_Helper56ca10(0x585eb8, 0x585ea4);
    Game_Helper57e820(0x93a520, 0x8aa920);
    Game_Helper57e820(0x930650, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x8c68c0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x7bf220, 0x8aa920 + 0x384);
    Game_Helper56ca10(a1, 0x585ec8);
    Game_Helper57e820(0x930980, 0x8aa920);
    Game_Helper57e820(0x7bf0f0, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x78e840, 0x8aa920 + 0x258);
    Game_Helper57e820(0x930d00, 0x8aa920 + 0x384);
    Game_Helper57e820(0x8bd0d0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8aa3c0, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x8aa600, 0x8aa920 + 0x708);
    Game_Helper57e820(0x939e70, 0x8aa920 + 0x834);
    Game_Helper57e820(0x8e31d0, 0x8aa920 + 0x960);
    Game_Helper57e820(0x939d30, 0x8aa920 + 0xa8c);
    Game_Helper57e820(0x8e36b0, 0x8aa920 + 0xbb8);
    Game_Helper57e820(0x94d690, 0x8aa920 + 0xce4);
    Game_Helper57e820(0x7be610, 0x8aa920 + 0xe10);
    Game_Helper57e820(0x7a07e0, 0x8aa920 + 0xf3c);
    Game_Helper57e820(0x8c8520, 0x8aa920 + 0x1068);
    Game_Helper57e820(0x8e1b00, 0x8aa920 + 0x1194);
    Game_Helper56ca10(a1, 0x585ee0);
    Game_Helper57e820(0x930370, 0x8aa920);
    Game_Helper57e820(0x8bd210, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x7a81b0, 0x8aa920 + 0x258);
    Game_Helper56ca10(a1, 0x585ef0);
    Game_Helper57e820(0x8c7fd0, 0x8aa920);
    Game_Helper57e820(0x8e2930, 0x8aa920 + 0x12c);
    Game_Helper56ca10(a1, 0x585f08);
    Game_Helper57e820(0x8c72c0, 0x8aa920);
    Game_Helper57e820(0x92e830, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x930e30, 0x8aa920 + 0x258);
    Game_Helper57e820(0x92fd20, 0x8aa920 + 0x384);
    Game_Helper57e820(0x7beec0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8bdc00, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x92e960, 0x8aa920 + 0x708);
    Game_Helper57e820(0x8e2540, 0x8aa920 + 0x834);
    Game_Helper57e820(0x8e3f30, 0x8aa920 + 0x960);
    Game_Helper57e820(0x8e2b70, 0x8aa920 + 0xa8c);
    Game_Helper57e820(0x798830, 0x8aa920 + 0xbb8);
    Game_Helper57e820(0x7a0240, 0x8aa920 + 0xce4);
    Game_Helper57e820(0x8c7640, 0x8aa920 + 0xe10);
    Game_Helper57e820(0x92ff80, 0x8aa920 + 0xf3c);
    Game_Helper57e820(0x951980, 0x8aa920 + 0x1068);
    Game_Helper57e820(0x8e2e90, 0x8aa920 + 0x1194);
    Game_Helper57e820(0x9304a0, 0x8aa920 + 0x12c0);
    Game_Helper57e820(0x9391b0, 0x8aa920 + 0x13ec);
    Game_Helper57e820(0x8aa740, 0x8aa920 + 0x1518);
    Game_Helper57e820(0x930100, 0x8aa920 + 0x1644);
    Game_Helper57e820(0x930bd0, 0x8aa920 + 0x1770);
    Game_Helper57e820(0x7bf360, 0x8aa920 + 0x189c);
    Game_Helper57e820(0x8e09d0, 0x8aa920 + 0x19c8);
    Game_Helper57e820(0x8e3510, 0x8aa920 + 0x1af4);
    Game_Helper57e820(0x94d180, 0x8aa920 + 0x1c20);
    Game_Helper57e820(0x8e27f0, 0x8aa920 + 0x1d4c);
    Game_Helper57e820(0x7a7f40, 0x8aa920 + 0x1e78);
    Game_Helper57e820(0x8c7d60, 0x8aa920 + 0x1fa4);
    Game_Helper57e820(0x8e2ca0, 0x8aa920 + 0x20d0);
    Game_Helper56ca10(0x8aa4f0, 0x585f20);
    Game_Helper57e820(0x938930, 0x8aa920);
    Game_Helper57e820(0x8bce20, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x8c8260, 0x8aa920 + 0x258);
    Game_Helper56ca10(0x8aa4f0, 0x585f30);
    for (iv = 0; iv < 0x13; iv++) {
        Game_Helper57e820(iv * 75 + 0x8c7770, iv * 300 + 0x8aa920);
    }
    Game_Helper56ca10(0x8aa4f0, 0x585f44);
    Game_Helper57e820(0x8e3e80, 0x8aa920);
    Game_Helper57e820(0x93a880, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x7bf0b0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x8c8280, 0x8aa920 + 0x384);
    Game_Helper57e820(0x8c84b0, 0x8aa920 + 0x4b0);
    Game_Helper56ca10(0x8aa4f0, 0x585f50);
    Game_Helper57e820(0x8e3190, 0x8aa920);
    Game_Helper57e820(0x939fa0, 0x8aa920 + 0x12c);
    Game_Helper56ca10(0x8aa4f0, 0x585f60);
    Game_Helper57e820(0x8c8100, 0x8aa920);
    Game_Helper56ca10(0x8aa4f0, 0x585f74);
    Game_Helper57e820(0x79fec0, 0x8aa920);
    Game_Helper56ca10(0x8aa4f0, 0x585f80);
    Game_Helper57e820(0x93a8d0, 0x8aa920);
    Game_Helper57e820(0x93a140, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x8c8470, 0x8aa920 + 0x258);
    Game_Helper57e820(0x930960, 0x8aa920 + 0x384);
    Game_Helper57e820(0x78e980, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8a93d0, 0x8aa920 + 0x5dc);
    Game_Helper56ca10(0x8aa4f0, 0x585f90);
    Game_Helper57e820(0x8c8400, 0x8aa920);
    Game_Helper57e820(0x93a1c0, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x7a0960, 0x8aa920 + 0x258);
    Game_Helper57e820(0x930b60, 0x8aa920 + 0x384);
    Game_Helper57e820(0x9308f0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x930af0, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x8c6ab0, 0x8aa920 + 0x708);
    Game_Helper57e820(0x94e930, 0x8aa920 + 0x834);
    Game_Helper56ca10(0x8aa4f0, 0x585fa0);
    Game_Helper57e820(0x8c7250, 0x8aa920);
    Game_Helper57e820(0x939420, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x94d5d0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x8bdda0, 0x8aa920 + 0x384);
    Game_Helper57e820(0x9312e0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8c6a40, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x7be5a0, 0x8aa920 + 0x708);
    Game_Helper57e820(0x8e3640, 0x8aa920 + 0x834);
    Game_Helper56ca10(0x8aa4f0, 0x585fb0);
    for (iv = 0; iv < 7; iv++) {
        Game_Helper57e820(iv * 150 + 0x8e4070, iv * 300 + 0x8aa920);
    }
    for (iv = 0; iv < 7; iv++) {
        Game_Helper57e820(iv * 150 + 0x8e0460, (iv * 4 + 0x1c) * 75 + 0x8aa920);
    }
    Game_Helper56ca10(0x8aa4f0, 0x585fc4);
    Game_Helper57e820(0x8bcf80, 0x8aa920);
    Game_Helper57e820(0x8bdd30, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x9305d0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x9388c0, 0x8aa920 + 0x384);
    Game_Helper57e820(0x93a4b0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x93a0d0, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x94cf70, 0x8aa920 + 0x708);
    Game_Helper57e820(0x7bf040, 0x8aa920 + 0x834);
    Game_Helper57e820(0x8c7430, 0x8aa920 + 0x960);
    Game_Helper57e820(0x7be9b0, 0x8aa920 + 0xa8c);
    Game_Helper57e820(0x92f260, 0x8aa920 + 0xbb8);
    Game_Helper57e820(0x8c69f0, 0x8aa920 + 0xce4);
    Game_Helper57e820(0x7bea60, 0x8aa920 + 0xe10);
    Game_Helper57e820(0x93a7a0, 0x8aa920 + 0xf3c);
    Game_Helper57e820(0x94d480, 0x8aa920 + 0x1068);
    Game_Helper57e820(0x7a0920, 0x8aa920 + 0x1194);
    Game_Helper57e820(0x8aa8e0, 0x8aa920 + 0x12c0);
    Game_Helper57e820(0x94e8e0, 0x8aa920 + 0x13ec);
    Game_Helper57e820(0x939bc0, 0x8aa920 + 0x1518);
    Game_Helper57e820(0x939cf0, 0x8aa920 + 0x1644);
    Game_Helper57e820(0x931350, 0x8aa920 + 0x1770);
    Game_Helper57e820(0x8e2dd0, 0x8aa920 + 0x189c);
    Game_Helper57e820(0x7a0600, 0x8aa920 + 0x19c8);
    Game_Helper56ca10(0x8aa4f0, 0x585fd8);
    Game_Helper57e820(0x7be560, 0x8aa920);
    Game_Helper57e820(0x939170, 0x8aa920 + 0x12c);
    Game_Helper57e820(0x92f3e0, 0x8aa920 + 0x258);
    Game_Helper57e820(0x8bd040, 0x8aa920 + 0x384);
    Game_Helper57e820(0x7a09d0, 0x8aa920 + 0x4b0);
    Game_Helper57e820(0x8c8b10, 0x8aa920 + 0x5dc);
    Game_Helper57e820(0x8e3380, 0x8aa920 + 0x708);
    Game_Helper57e820(0x930780, 0x8aa920 + 0x834);
    Game_Helper57e820(0x8bd000, 0x8aa920 + 0x960);
    Game_Helper57e820(0x7bf000, 0x8aa920 + 0xa8c);
    Game_Helper56cc4d(0x8aa4f0, 0x585fec);
    return Game_Helper57e820(0x7a0640, 0x8aa920);
}

// FUNCTION: SHANDALAR 0x00465dac
int Game_Fn465dac(int a1)
{
    if (a1 < 0 || a1 >= 0xd4) {
        return 0x5860b4;
    }
    return a1 * 60 + a1 * 240 + 0x93aa60;
}

// FUNCTION: SHANDALAR 0x00466049
int Game_Fn466049(int a1, int a2, int a3, int a4, int a5, int a6)
{
    return Game_Helper4660d6(a1, a2, 0, a3, a4, a5, a6, 0x25);
}

// FUNCTION: SHANDALAR 0x00466078
int Game_Fn466078(int a1, int a2, int a3, int a4, int a5, int a6)
{
    return Game_Helper4660d6(a1, a2, 0, a3, a4, a5, a6, 1);
}

// FUNCTION: SHANDALAR 0x004660a7
int Game_Fn4660a7(int a1, int a2, int a3, int a4, int a5, int a6)
{
    return Game_Helper4660d6(a1, 0, a2, a3, a4, a5, a6, 0x25);
}

// FUNCTION: SHANDALAR 0x00466d01
int Game_Fn466d01(int a1)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */
    int ih;   /* [ebp-12] */

    ig = g_game8c8b52[a1];
    ih = g_game8c8b51[a1];
    iv = g_game8c8b50[a1];
    return ih * 256 | ig | iv * 65536 | 0x2000000;
}

// FUNCTION: SHANDALAR 0x00467f35
int Game_Fn467f35(void)
{
    int iv;   /* [ebp-4] */

    iv = 0;
    return iv;
}

// FUNCTION: SHANDALAR 0x004683e4
int Game_Fn4683e4(int a1)
{
    int iv;   /* [ebp-4] */

    iv = 0;
    if (Game_Helper468498(1) != 0
        && Game_Helper468365(a1, 0) != 0) {
        iv = 1;
    } else {
        if (Game_Helper468498(2) != 0
            && Game_Helper468365(a1, 1) != 0) {
            iv = 1;
        } else {
            if (Game_Helper468498(4) != 0
                && Game_Helper468365(a1, 2) != 0) {
                iv = 1;
            }
        }
    }
    return iv;
}

// FUNCTION: SHANDALAR 0x0046e64b
int Game_Fn46e64b(int a1, int a2)
{
    int iv;   /* [ebp-4] */

    if (g_game8bd200 != 1
        && (g_gameCards[a2].flags & 0x2) != 0) {
        Game_Helper40ebb9(0x17);
    }
    for (iv = 0; iv < 0x1f4; iv++) {
        if (g_game8e0b00[a1][iv] == -1) {
            g_game8e0b00[a1][iv] = a2;
            return a2;
        }
    }
    return a2;
}

// FUNCTION: SHANDALAR 0x0046ec92
int Game_Fn46ec92(void)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x0046eca4
int Game_Fn46eca4(void)
{
    if (g_game586494 != 0) {
        g_game7898f0 = Game_Helper578c60() | g_game986d94;
        g_game7898f4 = g_game986d9c;
        g_game7898f8 = g_game986d98;
        return g_game986d98;
    }
    g_game7898f8 = 0;
    g_game7898f4 = g_game7898f8;
    g_game7898f0 = g_game7898f4;
    return g_game7898f4;
}

// FUNCTION: SHANDALAR 0x0046ed03
int Game_Fn46ed03(void)
{
    g_game78cefc++;
    if (g_game586494 != 0
        && g_game78cefc == 1) {
        return Game_Helper578c40();
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x0046ed9c
int Game_Fn46ed9c(int a1, int a2)
{
    return Game_Helper57a060(a2);
}

// FUNCTION: SHANDALAR 0x0046edb3
int Game_Fn46edb3(void)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x0046ed63
int Game_Fn46ed63(int a1, int a2)
{
    Game_Helper57c840(a1, 0x78cf10 + 0x7d0);
    return Game_Fn46ed9c(a2, 0x78cf10 + 0x7d0);
}

// FUNCTION: SHANDALAR 0x0046edc5
int Game_Fn46edc5(int a1)
{
    if (a1 == 0 || g_game8bd200 == 1) {
        return 0;
    } else {
        Game_Fn4ce955();
        while (Game_Fn4ce97d() < a1 * g_game5863ac) {
        }
        return 0;
    }
}
