/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x004ece40
int Game_Fn4ece40(int a1)
{
    if (a1 >= 0
        && a1 <= 9) {
        return a1 + 0x30;
    }
    if (a1 >= 0xa
        && a1 <= 0xf) {
        return a1 + 0x57;
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x004ecefd
int Game_Fn4ecefd(int a1)
{
    if (a1 > 0) {
        return 1;
    }
    if (a1 < 0) {
        return -1;
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x004ecf30
int Game_Fn4ecf30(int a1, int a2)
{
    int iv;   /* [ebp-4] */

    if (a1 < 0) {
        a1 = -a1;
    }
    if (a2 < 0) {
        a2 = -a2;
    }
    if (a2 < a1) {
        iv = a1 + a1 + a2;
    } else {
        iv = a2 + a2 + a1;
    }
    if (iv < 0) {
        iv = 0x7ffe;
    }
    return iv;
}

// FUNCTION: SHANDALAR 0x004ed0bd
int Game_Fn4ed0bd(void)
{
    int iv;   /* [ebp-4] */

    g_game789938 = 0;
    g_game78df68 = g_game789938;
    for (iv = 0; iv < 0x1f4; iv++) {
        if (deck[iv] != -1) {
            g_game789938++;
            if ((g_game97f1c1[iv] & 0x40) == 0) {
                g_game78df68++;
            }
        }
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x004ed19f
int Game_Fn4ed19f(void)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */
    int ih;   /* [ebp-12] */
    int ii;   /* [ebp-16] */

    Game_Helper579890(g_game5832b4, g_game5863b8 / 2 - 0x50, g_game5863bc / 3 - 0x3c, 0xa0, 0x78, g_game5832dc, 0, 0);
    for (iv = 3; iv <= 8; iv++) {
        ih = iv * g_game5863b8 / 8;
        ii = iv * g_game5863bc / 8;
        ig = (g_game5863bc / 2 * (iv - 2) + (8 - iv) * (g_game5863bc / 3)) / 6;
        Game_Helper579e40(g_game5832dc, 0, 0, 0xa0, 0x78, g_game5832b4, g_game5863b8 / 2 - ih / 2, ig - ii / 2, ih, ii);
    }
    Game_Helper579890(g_game5832b4, 0, 0, g_game5863b8, g_game5863bc, g_game5832dc, 0, 0);
    return Game_Helper4ecfa2();
}

// FUNCTION: SHANDALAR 0x004ed44b
int Game_Fn4ed44b(int a1)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */
    int ih;   /* [ebp-12] */
    int ii;   /* [ebp-16] */

    ih = Game_Fn5501fe(0x40);
    ii = Game_Fn5501fe(0x30);
    iv = Game_Fn5501fe(0x200);
    ig = Game_Fn5501fe(0x118);
    Game_Helper57c580(1, 0, g_game5863bc - 0x118, a1, 0);
    Game_Helper579e40(g_game5832dc, 0, g_game5863bc - 0x118, 0x200, 0x118, g_game5832dc, ih, ii, iv, ig);
    Game_Helper42fe00(g_game5832dc);
    return Game_Helper579890(g_game5832dc, ih, ii, iv, ig, g_game5832b4, ih, ii);
}

// FUNCTION: SHANDALAR 0x004ed525
int Game_Fn4ed525(int a1)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */
    int ih;   /* [ebp-12] */
    int ii;   /* [ebp-16] */
    int ij;   /* [ebp-20] */
    int ik;   /* [ebp-24] */
    int il;   /* [ebp-28] */
    int im;   /* [ebp-32] */

    ii = g_game5863bc - 0x118;
    Game_Helper57c580(1, 0, ii, a1, 0);
    iv = Game_Fn5501dc(0x100);
    ig = Game_Fn5501dc(0x8c);
    ih = Game_Fn5501dc(0x5e);
    for (ij = 2; ij <= 8; ij++) {
        il = iv * ij / 8;
        im = ig * ij / 8;
        ik = (g_game5863bc / 3 * (8 - ij) + (ij - 2) * (ig / 2)) / 6;
        Game_Helper579e40(g_game5832dc, 0, ii, 0x200, 0x118, g_game5832b4, g_game5863b8 / 2 - il / 2, ih - im / 2, il, im);
    }
    il = iv;
    im = ig;
    Game_Helper579e40(g_game5832dc, 0, ii, 0x200, 0x118, g_game5832dc, g_game5863b8 / 2 - il / 2, ih - im / 2, il, im);
    return Game_Helper42fe00(g_game5832b4);
}

// FUNCTION: SHANDALAR 0x004e4f5c
int Game_Fn4e4f5c(int a1, int a2, int a3, int a4, int a5)
{
    if ((g_gameCards[a5].flags & 0x2) != 0) {
        Game_AllocSlot(a3, a4, 1, a1, a2);
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x004ed06d
int Game_Fn4ed06d(int a1, int a2, int a3)
{
    int iv;   /* [ebp-4] */

    iv = a1;
    return Game_CopyBlock(a2, a1, a3);
}

// FUNCTION: SHANDALAR 0x004ed095
int Game_Fn4ed095(int a1, int a2, int a3)
{
    int iv;   /* [ebp-4] */

    iv = a2;
    return Game_CopyBlock(a2, a1, a3);
}

// FUNCTION: SHANDALAR 0x004ef07e
int Game_Fn4ef07e(void)
{
    Game_Fn5626b0(0x58ad7c, 0xf, 0x64, 0x64, 0);
    g_game7481d8 = -1;
    return Game_Fn5626b0(0x58ad7c, 0xf, 0x64, 0x64, 0);
}
