/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x004c16fb
int Game_Fn4c16fb(int a1, int a2)
{
    int iv;   /* [ebp-4] */

    iv = 0;
    if (a2 == 0) {
        if (a2 == a1 || g_gameCards[a1].mask == g_game93a780) {
            iv = 1;
        }
    }
    if (a2 == 1) {
        if (a2 == a1 || g_gameCards[a1].mask == g_game93a784) {
            iv = 1;
        }
    }
    if (a2 == 2) {
        if (a2 == a1 || g_gameCards[a1].mask == g_game93a788) {
            iv = 1;
        }
    }
    if (a2 == 3) {
        if (a2 == a1 || g_gameCards[a1].mask == g_game93a78c) {
            iv = 1;
        }
    }
    if (a2 == 4) {
        if (a2 == a1 || g_gameCards[a1].mask == g_game93a790) {
            iv = 1;
        }
    }
    return iv;
}

// FUNCTION: SHANDALAR 0x004c2501
int Game_Fn4c2501(int a1)
{
    int iv[500];   /* [ebp-2000] */

    return Game_Helper453b6c(iv, a1);
}

// FUNCTION: SHANDALAR 0x004c38a2
int Game_Fn4c38a2(void)
{
    Game_CopyBlock(0x8ca270, 0x74f1f0, 0x161e8);
    Game_CopyBlock(g_game73c00c * 72 + 0x594208, 0x765440, 0x480);
    Game_CopyBlock(0x8a9410, 0x5b4d60, 0xfa0);
    Game_CopyBlock(0x94d930, 0x5ad080, 0xfa0);
    Game_CopyBlock(0x8e0b00, 0x5aae80, 0xfa0);
    Game_CopyBlock(0x77d170, 0x5ad040, 0x40);
    Game_CopyBlock(0x7806a0, 0x5acff8, 0x40);
    Game_CopyBlock(0x77ed80, 0x5b6628, 0x40);
    Game_CopyBlock(0x74c790, 0x5b3fa0, 0x198);
    Game_CopyBlock(0x8c83f0, 0x5b4138, 8);
    Game_CopyBlock(0x7bfee0, 0x5b4d58, 8);
    Game_CopyBlock(0x8bce38, 0x5b5e18, 8);
    Game_CopyBlock(0x7be9e8, 0x5b5e08, 8);
    Game_CopyBlock(0x8e3ec0, 0x5b0e98, 0x60);
    Game_CopyBlock(0x8e2e10, 0x5ae020, 0x80);
    Game_CopyBlock(0x94eab0, 0x5b36c0, 0x7d0);
    Game_CopyBlock(0x8c9a90, 0x5b2600, 0x7d0);
    g_game8c83f8 = g_game5b66a8;
    g_game94d464 = g_game5b1180;
    g_game7a090c = g_game5b5d00;
    g_game8ca260 = g_game5b3e98;
    g_game8c83ec = g_game5aa690;
    Game_CopyBlock(0x94d2b0, 0x5b3640, 0x80);
    Game_CopyBlock(0x939310, 0x5b5d08, 0x100);
    Game_CopyBlock(0x93a940, 0x5b1008, 0x100);
    Game_CopyBlock(0x78e970, 0x5b6620, 8);
    g_gameEventCount = g_game5ace50;
    g_game7bf4c8 = g_game5b0e68;
    g_game94e968 = g_game5b35d4;
    Game_CopyBlock(0x94f3a0, 0x5ae8a8, 0x25c0);
    Game_CopyBlock(0x765420, 0x5b1150, 0x20);
    Game_CopyBlock(0x8e2690, 0x5b0e70, 0x20);
    g_game8c8274 = g_game5aae78;
    g_game8e26bc = g_game5b0e90;
    g_game93a798 = g_game5b21f8;
    g_game94e968 = g_game5b35d4;
    g_game74f1e0 = g_game5b4d48;
    g_game74d26c = g_game5b6618;
    g_game7bfe78 = g_game5b4d50;
    Game_CopyBlock(0x8c8650, 0x5abe20, 8);
    Game_CopyBlock(0x7be740, 0x5aae70, 8);
    return Game_Fn522660();
}

// FUNCTION: SHANDALAR 0x004c3b83
int Game_Fn4c3b83(void)
{
    Game_CopyBlock(0x765e30, 0x8ca270, 0x161e8);
    Game_CopyBlock(0x77c070, g_game73c00c * 72 + 0x594208, 0x480);
    Game_CopyBlock(0x5abeb0, 0x8a9410, 0xfa0);
    Game_CopyBlock(0x5b11d8, 0x94d930, 0xfa0);
    Game_CopyBlock(0x5b66b0, 0x8e0b00, 0xfa0);
    Game_CopyBlock(0x5b6668, 0x77d170, 0x40);
    Game_CopyBlock(0x5b1198, 0x7806a0, 0x40);
    Game_CopyBlock(0x5b1108, 0x77ed80, 0x40);
    Game_CopyBlock(0x5ace58, 0x74c790, 0x198);
    Game_CopyBlock(0x5aa698, 0x8c83f0, 8);
    Game_CopyBlock(0x5b1148, 0x7bfee0, 8);
    Game_CopyBlock(0x5b1170, 0x8bce38, 8);
    Game_CopyBlock(0x5b1178, 0x7be9e8, 8);
    Game_CopyBlock(0x5b35d8, 0x8e3ec0, 0x60);
    Game_CopyBlock(0x5b2178, 0x8e2e10, 0x80);
    Game_CopyBlock(0x5b5e20, 0x94eab0, 0x7d0);
    Game_CopyBlock(0x5aa6a0, 0x8c9a90, 0x7d0);
    g_game5b1000 = g_game8c83f8;
    g_game5b4d4c = g_game94d464;
    g_game5b1184 = g_game7a090c;
    g_game5b1190 = g_game8ca260;
    g_game5b3638 = g_game8c83ec;
    Game_CopyBlock(0x5abe28, 0x94d2b0, 0x80);
    Game_CopyBlock(0x5b3ea0, 0x939310, 0x100);
    Game_CopyBlock(0x5b0f00, 0x93a940, 0x100);
    Game_CopyBlock(0x5b1188, 0x78e970, 8);
    g_game5b3e90 = g_gameEventCount;
    g_game5ad038 = g_game7bf4c8;
    g_game5acff0 = g_game94d63c;
    Game_CopyBlock(0x5b65f8, 0x8e2690, 0x20);
    g_game5b3e94 = g_game8c8274;
    g_game5b5e10 = g_game8e26bc;
    g_game5b3e9c = g_game93a798;
    g_game5b4940 = g_game94e968;
    g_game5b4d48 = g_game74f1e0;
    g_game5b6618 = g_game74d26c;
    g_game5ae8a0 = g_game7bfe78;
    Game_CopyBlock(0x5b65f0, 0x8c8650, 8);
    return Game_CopyBlock(0x5b0ef8, 0x7be740, 8);
}

// FUNCTION: SHANDALAR 0x004c3e34
int Game_Fn4c3e34(void)
{
    Game_CopyBlock(0x8ca270, 0x765e30, 0x161e8);
    Game_CopyBlock(g_game73c00c * 72 + 0x594208, 0x77c070, 0x480);
    Game_CopyBlock(0x8a9410, 0x5abeb0, 0xfa0);
    Game_CopyBlock(0x94d930, 0x5b11d8, 0xfa0);
    Game_CopyBlock(0x8e0b00, 0x5b66b0, 0xfa0);
    Game_CopyBlock(0x77d170, 0x5b6668, 0x40);
    Game_CopyBlock(0x7806a0, 0x5b1198, 0x40);
    Game_CopyBlock(0x77ed80, 0x5b1108, 0x40);
    Game_CopyBlock(0x74c790, 0x5ace58, 0x198);
    Game_CopyBlock(0x8c83f0, 0x5aa698, 8);
    Game_CopyBlock(0x7bfee0, 0x5b1148, 8);
    Game_CopyBlock(0x8bce38, 0x5b1170, 8);
    Game_CopyBlock(0x7be9e8, 0x5b1178, 8);
    Game_CopyBlock(0x8e3ec0, 0x5b35d8, 0x60);
    Game_CopyBlock(0x8e2e10, 0x5b2178, 0x80);
    Game_CopyBlock(0x94eab0, 0x5b5e20, 0x7d0);
    Game_CopyBlock(0x8c9a90, 0x5aa6a0, 0x7d0);
    g_game8c83f8 = g_game5b1000;
    g_game94d464 = g_game5b4d4c;
    g_game7a090c = g_game5b1184;
    g_game8ca260 = g_game5b1190;
    g_game8c83ec = g_game5b3638;
    Game_CopyBlock(0x94d2b0, 0x5abe28, 0x80);
    Game_CopyBlock(0x939310, 0x5b3ea0, 0x100);
    Game_CopyBlock(0x93a940, 0x5b0f00, 0x100);
    Game_CopyBlock(0x78e970, 0x5b1188, 8);
    g_gameEventCount = g_game5b3e90;
    g_game7bf4c8 = g_game5ad038;
    g_game94d63c = g_game5acff0;
    Game_CopyBlock(0x8e2690, 0x5b65f8, 0x20);
    g_game8c8274 = g_game5b3e94;
    g_game8e26bc = g_game5b5e10;
    g_game93a798 = g_game5b3e9c;
    g_game94e968 = g_game5b4940;
    g_game74f1e0 = g_game5b4d48;
    g_game74d26c = g_game5b6618;
    g_game7bfe78 = g_game5ae8a0;
    Game_CopyBlock(0x8c8650, 0x5b65f0, 8);
    return Game_CopyBlock(0x7be740, 0x5b0ef8, 8);
}

// FUNCTION: SHANDALAR 0x004c40e5
int Game_Fn4c40e5(void)
{
    g_game74842c = 0;
    g_game5b2dd0[g_game74842c] = 0x63;
    return g_game74842c;
}

// FUNCTION: SHANDALAR 0x004c4364
int Game_Fn4c4364(void)
{
    int iv;   /* [ebp-4] */

    for (iv = 0; iv < g_game74842c; iv++) {
        g_game5b2dd0[iv] = g_game5b31d0[iv];
        g_game5ae0a0[iv] = g_game5ae4a0[iv];
        g_game5b4140[iv] = g_game5b4540[iv];
        g_game5b2200[iv] = g_game5b4948[iv];
    }
    g_game5b2dd0[g_game74842c] = 0x63;
    if (g_game5b2dd0[0] == 0x63) {
        g_game5b7650 = g_game74842c;
    }
    g_game765e24 = 1;
    return g_game74842c;
}

// FUNCTION: SHANDALAR 0x004c4415
int Game_Fn4c4415(void)
{
    return g_game74842c;
}

// FUNCTION: SHANDALAR 0x004c69f3
int Game_Fn4c69f3(int a1)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004c8381
int Game_Fn4c8381(int a1)
{
    if (a1 >= 0x61
        && a1 <= 0x66) {
        return a1 - 0x57;
    }
    return a1 - 0x30;
}

// FUNCTION: SHANDALAR 0x004c8bc5
int Game_Fn4c8bc5(int a1)
{
    g_game5b7b6c = a1;
    g_game982540 = g_game5a1814;
    g_game748428 = (int)Game_Callback4c8bec;
    return g_game5a1814;
}

// FUNCTION: SHANDALAR 0x004ce955
int Game_Fn4ce955(void)
{
    int iv;   /* [ebp-4] */

    iv = g_game589df0;
    g_game589df0 = 0;
    return iv;
}

// FUNCTION: SHANDALAR 0x004ce97d
int Game_Fn4ce97d(void)
{
    return g_game589df0;
}

// FUNCTION: SHANDALAR 0x004cea02
int Game_Fn4cea02(void)
{
    if (Game_Helper417dc6(0x58a168) == 0) {
        g_game748408 = 1;
    } else {
        g_game748408 = 0;
    }
    g_game74840c = 0;
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceacb
int Game_Fn4ceacb(void)
{
    return Game_Helper4cea4c(0, 0);
}

// FUNCTION: SHANDALAR 0x004ceb0a
int Game_Fn4ceb0a(int a1, int a2, int a3)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceb15
int Game_Fn4ceb15(int a1, int a2, int a3)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceb20
int Game_Fn4ceb20(int a1, int a2, int a3, int a4)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceb2b
int Game_Fn4ceb2b(int a1, int a2, int a3, int a4)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceb36
int Game_Fn4ceb36(void)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004ceb41
int Game_Fn4ceb41(int a1, int a2, int a3, int a4)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004c410a
int Game_Fn4c410a(void)
{
    int iv;   /* [ebp-4] */

    g_game951970 = 0;
    g_game74842c = g_game951970;
    g_game77edc0 = -1;
    for (iv = 0; iv < 0x100; iv++) {
        g_game5b31d0[iv] = 0x63;
    }
    Game_Fn4c38a2();
    if (g_game8bd200 != 1) {
        g_game78e82c = -1;
        return Game_Fn4c38a2();
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x004cdd1b
int Game_Fn4cdd1b(int a1)
{
    if (a1 == 1 && g_game939ce0 != 0 || a1 == 0 && g_game939ce4 != 0) {
        return 1;
    }
    return 0;
}
