/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x00430994
int Game_Fn430994(void)
{
    Game_Helper4ccd9e(0x58308c);
    Game_Helper56dc9c(0x5830a0);
    Game_Helper550dba(0x5830b8);
    Game_Helper46ef07(0x5830d4);
    Game_Helper4bac17(0x5830e8);
    Game_Helper57456b(0x5830fc);
    Game_Helper559ff4(0x583110);
    Game_Helper55a13b(0x58312c);
    Game_Helper504be8(0x583150);
    Game_Helper4c19a2(0x58316c);
    Game_Helper50d809(0x583184);
    Game_Helper45cba4(0x5831a0);
    Game_Helper4c8f49(0x5831b8);
    Game_Helper4261ae(0x5831d4);
    Game_Helper556385(0x5831e8);
    Game_Helper4c6c10(0x583204);
    Game_Fn4c69f3(0x583224);
    Game_Helper4cc0c1(0x583240);
    return Game_Helper46933c(0x583254);
}

// FUNCTION: SHANDALAR 0x00430a96
int Game_Fn430a96(int a1, int a2, int a3, int a4)
{
    int iv;   /* [ebp-4] */

    iv = a2;
    return 0;
}

// FUNCTION: SHANDALAR 0x00430e00
int Game_Fn430e00(int a1, int a2, int a3, int a4, int a5)
{
    return Game_Helper5796c0(g_game5832b4, a1, a2, a3, a4, a5);
}

// FUNCTION: SHANDALAR 0x00430f69
int Game_Fn430f69(int a1, int a2, int a3, int a4)
{
    a2 = a2 * g_game5863b8 / 0x140;
    a3 = g_game5863bc * a3 / 0xf0;
    return Game_Helper43104f(a1, a2, a3, a4);
}

// FUNCTION: SHANDALAR 0x00430fb5
int Game_Fn430fb5(int a1, int a2, int a3, int a4)
{
    a2 = a2 * g_game5863b8 / 0x140;
    a3 = a3 * g_game5863bc / 0xf0;
    return Game_Fn4310a4(a1, a2, a3, a4);
}

// FUNCTION: SHANDALAR 0x00431002
int Game_Fn431002(int a1, int a2, int a3, int a4)
{
    a2 = a2 * g_game5863b8 / 0x140;
    a3 = a3 * g_game5863bc / 0xf0;
    return Game_Helper430ef4(a1, a2, a3, a4);
}

// FUNCTION: SHANDALAR 0x004310a4
int Game_Fn4310a4(int a1, int a2, int a3, int a4)
{
    if (a4 != 0) {
        Game_Helper43104f(a1, a2, a3 + 1, 0);
    }
    return Game_Helper43104f(a1, a2, a3, a4);
}

// FUNCTION: SHANDALAR 0x004311d2
int Game_Fn4311d2(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
    return Game_Helper579890(a1, a2 * g_game5863b8 / 0x140, a3 * g_game5863bc / 0xf0, a4 * g_game5863b8 / 0x140, a5 * g_game5863bc / 0xf0, a6, a7 * g_game5863b8 / 0x140, a8 * g_game5863bc / 0xf0);
}

// FUNCTION: SHANDALAR 0x0043125f
int Game_Fn43125f(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
    return Game_Helper579bf0(a1, g_game5863b8 * a2 / 0x140, g_game5863bc * a3 / 0xf0, a4 * g_game5863b8 / 0x140, a5 * g_game5863bc / 0xf0, a6, a7 * g_game5863b8 / 0x140, a8 * g_game5863bc / 0xf0);
}

// FUNCTION: SHANDALAR 0x004312ea
int Game_Fn4312ea(int a1, int a2, int a3, int a4, int a5, int a6)
{
    return Game_Helper5797e0(a1, a2 * g_game5863b8 / 0x140, a3 * g_game5863bc / 0xf0, a4 * g_game5863b8 / 0x140, a5 * g_game5863bc / 0xf0, a6);
}

// FUNCTION: SHANDALAR 0x00431351
int Game_Fn431351(int a1, int a2, int a3, int a4, int a5, int a6)
{
    a2 = a2 * g_game5863b8 / 0x280;
    a3 = g_game5863bc * a3 / 0x1e0;
    a5 = a5 * g_game5863b8 / 0x280;
    a6 = a6 * g_game5863bc / 0x1e0;
    return Game_Helper57bfa0(a1, a2, a3, a5, a6, a4);
}

// FUNCTION: SHANDALAR 0x004313cf
int Game_Fn4313cf(int a1, int a2, int a3, int a4, int a5, int a6)
{
    return Game_Helper57bfa0(a1, a2 * g_game5863b8 / 0x140, a3 * g_game5863bc / 0xf0, a4 * g_game5863b8 / 0x140, a5 * g_game5863bc / 0xf0, a6);
}

// FUNCTION: SHANDALAR 0x00431436
int Game_Fn431436(int a1, int a2, int a3, int a4, int a5)
{
    return Game_Helper5797e0(g_game5832b4, a1, a2, a3 - a1 + 1, a4 - a2 + 1, a5);
}

// FUNCTION: SHANDALAR 0x0043146b
int Game_Fn43146b(int a1, int a2)
{
    if (a1 >= 0x40 || a1 < 0) {
        a1 = 0;
    }
    if (a2 >= 0x40 || a2 < 0) {
        a2 = 0;
    }
    return Game_Helper5795f0(g_game583304, a1, a2) & 0xf;
}

// FUNCTION: SHANDALAR 0x004314ca
int Game_Fn4314ca(int a1, int a2)
{
    if (a1 >= 0x40 || a1 < 0) {
        return 0;
    }
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    return Game_Helper5795f0(g_game583304, a1, a2);
}

// FUNCTION: SHANDALAR 0x00431526
int Game_Fn431526(int a1, int a2, int a3)
{
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    if (a3 >= 0x40 || a3 < 0) {
        return 0;
    }
    return Game_Helper579760(g_game583304, a2, a3, Game_Helper5795f0(g_game583304, a2, a3) | a1);
}

// FUNCTION: SHANDALAR 0x00431593
int Game_Fn431593(int a1, int a2, int a3)
{
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    if (a3 >= 0x40 || a3 < 0) {
        return 0;
    }
    return Game_Helper579760(g_game583304, a2, a3, Game_Helper5795f0(g_game583304, a2, a3) & ~a1);
}

// FUNCTION: SHANDALAR 0x0043174d
int Game_Fn43174d(int a1, int a2, int a3)
{
    if (a1 >= 0x40 || a1 < 0) {
        return 0;
    }
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    Game_Helper579760(g_game583304, a1, a2 + 0x40, Game_Helper5795f0(g_game583304, a1, a2 + 0x40) | 1 << a3 - 1);
    Game_Fn431526(0x20, a1, a2);
    a1 += g_game5862d8[a3];
    a2 += g_game586340[a3];
    a3 = (a3 + 3 & 7) + 1;
    Game_Helper579760(g_game583304, a1, a2 + 0x40, Game_Helper5795f0(g_game583304, a1, a2 + 0x40) | 1 << a3 - 1);
    return Game_Fn431526(0x20, a1, a2);
}

// FUNCTION: SHANDALAR 0x00431859
int Game_Fn431859(int a1, int a2, int a3)
{
    if (a1 >= 0x40 || a1 < 0) {
        return 0;
    }
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    return Game_Helper5795f0(g_game583304, a1, a2 + 0x40) & 1 << a3 - 1;
}

// FUNCTION: SHANDALAR 0x00433527
int Game_Fn433527(void)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x00436ad2
int Game_Fn436ad2(void)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x00430f2f
int Game_Fn430f2f(int a1, int a2, int a3, int a4)
{
    Game_Helper430ef4(a1, a2, a3 + 1, 0);
    return Game_Helper430ef4(a1, a2, a3, a4);
}

// FUNCTION: SHANDALAR 0x00431148
int Game_Fn431148(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8)
{
    return Game_Helper579890(a1, a2 * g_game5863b8 / 0x140, g_game5863bc * a3 / 0xf0, g_game5863b8 * a4 / 0x140, g_game5863bc * a5 / 0xf0, a6, a7 * g_game5863b8 / 0x140, a8 * g_game5863bc / 0xf0);
}

// FUNCTION: SHANDALAR 0x00431604
int Game_Fn431604(int a1, int a2)
{
    if (a1 >= 0x40 || a1 < 0) {
        return 0;
    }
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    return Game_Helper5795f0(g_game583304, a1 + 0x40, a2);
}

// FUNCTION: SHANDALAR 0x00431663
int Game_Fn431663(int a1, int a2, int a3)
{
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    if (a3 >= 0x40 || a3 < 0) {
        return 0;
    }
    return Game_Helper579760(g_game583304, a2 + 0x40, a3, Game_Helper5795f0(g_game583304, a2 + 0x40, a3) | a1);
}

// FUNCTION: SHANDALAR 0x004316d6
int Game_Fn4316d6(int a1, int a2, int a3)
{
    if (a2 >= 0x40 || a2 < 0) {
        return 0;
    }
    if (a3 >= 0x40 || a3 < 0) {
        return 0;
    }
    return Game_Helper579760(g_game583304, a2 + 0x40, a3, Game_Helper5795f0(g_game583304, a2 + 0x40, a3) & ~a1);
}

// FUNCTION: SHANDALAR 0x004318c7
int Game_Fn4318c7(int a1, int a2)
{
    if (a1 < 0 || a1 >= 0x40) {
        return 0;
    }
    if (a2 < 0 || a2 >= 0x40) {
        return 0;
    }
    return 1;
}
