/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x00424c13
int Game_Fn424c13(void)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */

    for (iv = 0; iv < 0x10; iv++) {
        for (ig = 0; ig < 0x10; ig++) {
            g_game5a7c08[iv][ig] = 0;
        }
    }
    return ig;
}

// FUNCTION: SHANDALAR 0x00426ddf
int Game_Fn426ddf(int a1)
{
    if (a1 == 1 && g_game939ce0 != 0 || a1 == 0 && g_game939ce4 != 0) {
        return 1;
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x00426efc
int Game_Fn426efc(void)
{
    if (g_game8bd200 == 1) {
        return 1;
    }
    if (g_game77e58c != 0) {
        return 1;
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x0042804f
int Game_Fn42804f(int a1)
{
    Game_Helper57e820(0x5a8290, a1);
    return Game_Fn56c779(0x5a8290);
}

// FUNCTION: SHANDALAR 0x004288f1
int Game_Fn4288f1(int a1, int a2)
{
    if (g_game8bd200 == 1) {
        return 0;
    }
    return Game_Fn4289b1(a1, a2, 0xba, 0x33);
}

// FUNCTION: SHANDALAR 0x004289b1
int Game_Fn4289b1(int a1, int a2, int a3, int a4)
{
    return 0;
}

// FUNCTION: SHANDALAR 0x004290e2
int Game_Fn4290e2(int a1, int a2)
{
    if (g_game789930 < 0x7d0) {
        g_game7817f0[g_game789930][0] = a1;
        g_game7817f0[g_game789930][1] = a2;
        g_game7817f0[g_game789930][2] = g_game5911f8 / 0x20;
        g_game7817f0[g_game789930][3] = g_game5911fc / 0x20;
        g_game789930++;
        return g_game5911fc / 0x20;
    }
    return 0;
}

// FUNCTION: SHANDALAR 0x0042e1e2
int Game_Fn42e1e2(void)
{
    int iv;   /* [ebp-4] */
    int ig;   /* [ebp-8] */

    if (g_game581ea8 != 0) {
        return 0;
    } else {
        iv = 0;
        ig = 0xffffff01;
        while (iv < 0x200) {
            g_game9523f0[iv] = ig * ig;
            iv++;
            ig++;
        }
        g_game581ea8 = 1;
        return 1;
    }
}

// FUNCTION: SHANDALAR 0x0042fde0
int Game_Fn42fde0(int a1)
{
    return a1 & 0xf8f8f8;
}

// FUNCTION: SHANDALAR 0x0042ffd0
int Game_Fn42ffd0(int a1)
{
    int iv;   /* [ebp-4] */

    g_game930644 = 1;
    g_game939410 = 0;
    g_game93a798 = -1;
    g_game8bd200 = 0;
    g_game79ff88 = 0;
    Game_Helper559999();
    g_game8e448c = 4;
    g_game8c7e8c = a1;
    if (g_game8c7e8c != -1) {
        Game_Helper56ca10(0x582da4, 0x582d98);
        Game_Helper57e820(0x93a800, (g_game8c7e8c * 4 + 0xfffffffc) * 75 + 0x8aa920);
    } else {
        Game_Helper56ca10(0x8aa4f0, 0x582db0);
        Game_Helper57e820(0x93a800, 0x8aa920);
    }
    if (Game_Helper5472f1() != 0) {
        iv = Game_Helper544e8f();
        Game_Helper5474e1();
    }
    return iv;
}
