/* Ordinary Shandalar game code, reconstructed by gamewire.
 *
 * Neither card scripts nor the helpers they call -- just the rest of .text.
 * Generated by pattern-matching the disassembly; the reccmp score is the check.
 * Names are addresses because nothing here establishes meaning yet.
 */
#include "game/gamefns.h"

// FUNCTION: SHANDALAR 0x004bb458
int Game_Fn4bb458(int a1)
{
    int iv;   /* [ebp-4] */

    for (iv = 0; g_game73c00c + 0x10 > iv; iv++) {
        if (g_gameCards[iv].mask == g_game5863c0[a1][0]) {
            return iv;
        }
    }
    return iv;
}

// FUNCTION: SHANDALAR 0x004be4c4
int Game_Fn4be4c4(int a1)
{
    int iv;   /* [ebp-4] */

    iv = g_game5863b8;
    if (iv != 0x280) {
        if (iv != 0x320) {
            if (iv == 0x400) {
                Game_Helper57e820(0x78cf10, 0x589994);
            }
        } else {
            Game_Helper57e820(0x78cf10, 0x58998c);
        }
    } else {
        Game_Helper57e820(0x78cf10, 0x589984);
    }
    Game_Helper57e826(0x78cf10, a1);
    return 0x78cf10;
}
