/* Helpers called by the card scripts, reconstructed by helpergen.
 *
 * These are the shared core of the card system -- the one at 0x0056ca10 is
 * called by 302 of the 608 scripts. Generated by pattern-matching the
 * disassembly, not written by hand; the reccmp score is the check. Names are
 * addresses because nothing here establishes meaning yet.
 */
#include "game/helpers.h"

/* called by 1 of the 608 card scripts */
// FUNCTION: SHANDALAR 0x004a008c
int Game_Helper4a008c(int a1)
{
    int v4;
    int v8;

    if (Game_Helper4c0efa(a1, a1, a1, 0x200, 1, 0, 0, 0, 0, 0, -1, -1, -1, -1, 0, 0, 0, 0x8aa920, 0, &v8) != 0) {
        if (g_game8bd200 != 1) {
            Game_Helper40ebb9(0xf);
        }
        Game_Helper46d8c1(v8, v4, 3);
        return 1;
    }
    return 0;
}

/* called by 2 of the 608 card scripts */
// FUNCTION: SHANDALAR 0x004a0403
int Game_Helper4a0403(int a1)
{
    int v4;
    int v8;

    if (Game_Helper4c0efa(a1, a1, a1, 0x200, 0x40, 0, 0, 0, 0, 0, -1, -1, -1, -1, 0, 0, 0, 0x8aa920, 0, &v8) != 0) {
        if (g_game8bd200 != 1) {
            Game_Helper40ebb9(0xf);
        }
        Game_Helper46d8c1(v8, v4, 3);
        return 1;
    }
    return 0;
}
