#!/usr/bin/env python3
"""
Generate Makefile.gen from whatever translation units currently exist in src/.

Written because the reconstruction is being landed in waves: a hand-maintained
object list breaks the build every time a TU is added or is still in flight.
The flag choice per TU is not cosmetic -- it is the measured-correct one:

  /O2  sidlib (sprite, lib, text, fileio, pcxw, palette) and stubs.c
  /Od  everything in the game layer, plus window.c (the one TU the original
       demonstrably built unoptimised)

Header dependencies mirror what each TU includes, so touching gameslot.h
rebuilds the game layer and nothing else.

Usage: genmake.py            (writes Makefile.gen next to Makefile)
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "src")

SIDLIB_HDRS = {
    "sprite": r"src\include\sidlib\sidsprite.h src\include\sidlib\sidcore.h",
    "lib": r"src\include\sidlib\sidgfx.h src\include\sidlib\sidcore.h",
    "text": r"src\include\sidlib\sidtext.h src\include\sidlib\sidcore.h",
    "fileio": r"src\include\sidlib\sidfileio.h src\include\sidlib\sidcore.h",
    "pcxw": r"src\include\sidlib\sidfileio.h",
    "palette": r"src\include\sidlib\sidpalette.h",
}
GAMESLOT = r"src\include\game\gameslot.h"
GAMEFNS = r"src\include\game\gamefns.h"
HELPERS = r"src\include\game\helpers.h"


def hdrs_for(name, path):
    """Header prerequisites, derived from the TU's own #include lines."""
    try:
        text = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return GAMESLOT
    out = []
    if '"game/helpers.h"' in text:
        out.append(HELPERS)
    if '"game/gamefns.h"' in text:
        out.append(GAMEFNS)
    if '"game/gameslot.h"' in text:
        out.append(GAMESLOT)
    for k, v in (("sidsprite", r"src\include\sidlib\sidsprite.h"),
                 ("sidgfx", r"src\include\sidlib\sidgfx.h"),
                 ("sidtext", r"src\include\sidlib\sidtext.h"),
                 ("sidfileio", r"src\include\sidlib\sidfileio.h"),
                 ("sidpalette", r"src\include\sidlib\sidpalette.h"),
                 ("sidwindow", r"src\include\sidlib\sidwindow.h"),
                 ("sidcore", r"src\include\sidlib\sidcore.h")):
        if f'"sidlib/{k}.h"' in text:
            out.append(v)
    return " ".join(dict.fromkeys(out))


def main():
    units = []          # (obj_name, src_path_win, flags_var, headers)

    for name in SIDLIB_HDRS:
        p = os.path.join(SRC, "sidlib", name + ".c")
        if os.path.exists(p):
            units.append((name, rf"src\sidlib\{name}.c", "CFLAGS",
                          hdrs_for(name, p) or SIDLIB_HDRS[name]))

    p = os.path.join(SRC, "window.c")
    if os.path.exists(p):
        units.append(("window", r"src\window.c", "CFLAGS_OD", hdrs_for("window", p)))
    p = os.path.join(SRC, "deck", "deck.c")
    if os.path.exists(p):
        units.append(("deck", r"src\deck\deck.c", "CFLAGS_OD", hdrs_for("deck", p)))

    gdir = os.path.join(SRC, "game")
    if os.path.isdir(gdir):
        for fn in sorted(os.listdir(gdir)):
            if not fn.endswith(".c"):
                continue
            name = fn[:-2]
            p = os.path.join(gdir, fn)
            units.append((name, rf"src\game\{fn}", "CFLAGS_OD", hdrs_for(name, p)))

    p = os.path.join(SRC, "stubs.c")
    if os.path.exists(p):
        units.append(("stubs", r"src\stubs.c", "CFLAGS", hdrs_for("stubs", p)))

    L = ["# GENERATED by tools/progress/genmake.py -- do not edit by hand.",
         "# Rerun genmake.py after adding or removing a translation unit.",
         ""]
    objs = " \\\n    ".join(f"$(OUTDIR)\\{n}.obj" for n, _, _, _ in units)
    L += [f"OBJS = \\\n    {objs}", ""]
    for name, src, flags, hdr in units:
        L.append(f"$(OUTDIR)\\{name}.obj: {src} {hdr}".rstrip())
        L.append(f"\t$(CC) $({flags}) /Fo$@ {src}")
        L.append("")

    out = os.path.join(ROOT, "Makefile.gen")
    with open(out, "w", encoding="ascii", newline="\r\n") as fh:
        fh.write("\n".join(L))
    print(f"genmake: {len(units)} translation units -> Makefile.gen")


if __name__ == "__main__":
    main()
